// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/resize.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResizeTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Dir           string                 `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Resize        bool                   `protobuf:"varint,3,opt,name=resize,proto3" json:"resize,omitempty"`
	Progressive   bool                   `protobuf:"varint,4,opt,name=progressive,proto3" json:"progressive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTask) Reset() {
	*x = ResizeTask{}
	mi := &file_proto_resize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTask) ProtoMessage() {}

func (x *ResizeTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTask.ProtoReflect.Descriptor instead.
func (*ResizeTask) Descriptor() ([]byte, []int) {
	return file_proto_resize_proto_rawDescGZIP(), []int{0}
}

func (x *ResizeTask) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ResizeTask) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ResizeTask) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *ResizeTask) GetResize() bool {
	if x != nil {
		return x.Resize
	}
	return false
}

func (x *ResizeTask) GetProgressive() bool {
	if x != nil {
		return x.Progressive
	}
	return false
}

var File_proto_resize_proto protoreflect.FileDescriptor

const file_proto_resize_proto_rawDesc = "" +
	"\n" +
	"\x12proto/resize.proto\x12\x0eimage_pipeline\"\x87\x01\n" +
	"\n" +
	"ResizeTask\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\tR\x03dir\x12\x16\n" +
	"\x06resize\x18\x03 \x01(\bR\x06resize\x12 \n" +
	"\vprogressive\x18\x04 \x01(\bR\vprogressiveB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_resize_proto_rawDescOnce sync.Once
	file_proto_resize_proto_rawDescData []byte
)

func file_proto_resize_proto_rawDescGZIP() []byte {
	file_proto_resize_proto_rawDescOnce.Do(func() {
		file_proto_resize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resize_proto_rawDesc), len(file_proto_resize_proto_rawDesc)))
	})
	return file_proto_resize_proto_rawDescData
}

var file_proto_resize_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_resize_proto_goTypes = []any{
	(*ResizeTask)(nil), // 0: image_pipeline.ResizeTask
}
var file_proto_resize_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_resize_proto_init() }
func file_proto_resize_proto_init() {
	if File_proto_resize_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resize_proto_rawDesc), len(file_proto_resize_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_resize_proto_goTypes,
		DependencyIndexes: file_proto_resize_proto_depIdxs,
		MessageInfos:      file_proto_resize_proto_msgTypes,
	}.Build()
	File_proto_resize_proto = out.File
	file_proto_resize_proto_goTypes = nil
	file_proto_resize_proto_depIdxs = nil
}
